name: Build and push docker images

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/subjects
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/subjects-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/subjects-backend:latest

    paths:
      - 'backend/subjects/**'

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/subjects
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/subjects-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/subjects-frontend:latest

    paths:
      - 'frontend/subjects/**'
